account/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth.views import LogoutView,LoginView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView

urlpatterns = [
 #path('login/', views.user_login, name='login'),
 path('', views.dashboard, name='dashboard'),path('', views.dashboard, name='dashboard'),
 path('login/',LoginView.as_view(template_name='account/registration/login.html'),name="login"),
 path('logout/',LogoutView.as_view(template_name='account/registration/logged_out.html'),name="logout"),
 path('passwordchange/',PasswordChangeView.as_view(template_name='account/registration/password_change_form.html'),name="password_change"),
 path('passwordchangedone/',PasswordChangeDoneView.as_view(template_name='account/registration/password_change_done.html'),name="password_change_done"),
 path('passwordreset/',PasswordResetView.as_view(template_name='account/registration/password_reset_form.html'),name="password_reset"),
 path('passwordresetdone/',PasswordResetDoneView.as_view(template_name='account/registration/password_reset_done.html'),name="password_reset_done"),
 re_path(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',PasswordResetConfirmView.as_view(template_name='account/registration/password_reset_confirm.html'),name="password_reset_confirm"),
 
 path('register/', views.register, name='register'),
 path('edit/', views.edit, name='edit'),

 path('users/', views.user_list, name='user_list'),
 path('users/(<str:username>', views.user_detail, name='user_detail'),

 path('users/follow/', views.user_follow, name='user_follow'),
 
]

bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls') ),
    path('images/', include(('images.urls', 'images'), namespace='images')),
    path('social-auth/', include('social.apps.django_app.urls', namespace='social')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('create/', views.image_create, name='create'),
path('detail/<int:id>/<str:slug>/', views.image_detail, name='detail'),
path('like/', views.image_like, name='like'),
path('', views.image_list, name='list'),
path('ranking/', views.image_ranking, name='create'),

]

account/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)
 
    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)


class Contact(models.Model):
    user_from = models.ForeignKey(User, related_name='rel_from_set', on_delete=models.CASCADE)
    user_to = models.ForeignKey(User, related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    
    class Meta:
        ordering = ('-created',)
 
    def __str__(self):
        return '{} follows {}'.format(self.user_from, self.user_to)
        
# Add following field to User dynamically
User.add_to_class('following', models.ManyToManyField('self', through=Contact, related_name='followers', symmetrical=False))

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class LoginForm(forms.Form):
 username = forms.CharField()
 password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

account/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm
from .models import Profile
from django.contrib.auth.decorators import login_required

from django.contrib import messages

from .forms import LoginForm, UserRegistrationForm,UserEditForm, ProfileEditForm

from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User


from django.http import JsonResponse
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from .models import Contact
from actions.utils import create_action
from actions.models import Action
from django.views.decorators.csrf import csrf_exempt

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
                
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})



@login_required
def dashboard(request):
    # Display all actions by default
    actions = Action.objects.filter(user=request.user)
    following_ids = request.user.following.values_list('id',flat=True)
    if following_ids:
        # If user is following others, retrieve only their actions
        actions = actions.filter(user_id__in=following_ids).select_related('user', 'user__profile').prefetch_related('target')
    actions = actions[:10]
    return render(request,'account/dashboard.html',{'section': 'dashboard','actions': actions})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
        # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            profile = Profile.objects.create(user=new_user)
            create_action(new_user, 'has created an account')

        return render(request,'register_done.html',{'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
        print(user_form)
        return render(request,'register.html',{'user_form': user_form})



@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
        data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,data=request.POST,files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
        
    return render(request,'account/edit.html',{'user_form': user_form,'profile_form': profile_form})



@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)
    return render(request,'account/user/list.html',{'section': 'people','users': users})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User,username=username,is_active=True)
    return render(request,'account/user/detail.html', {'section': 'people','user': user})




@ajax_required
@login_required
@require_POST
def user_follow(request):
    user_id = request.POST.get('id')
    print(user_id)
    action = request.POST.get('action')
    print(action)
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                data=Contact.objects.get_or_create(user_from=request.user,user_to=user)
                create_action(request.user, 'is following', user)
            else:
                data=Contact.objects.filter(user_from=request.user,user_to=user).delete()
                print(data)
            return JsonResponse({'status':'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status':'ko'})
    return JsonResponse({'status':'ko'})

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">

    {% include 'cdnlines.html' %}
    
</head>
<body>
    <div id="header" class="bg-primary">
        <span class="logo" style="color:rgb(230, 171, 222); font-weight: 600; font-family: cooper;">Bookmarks</span>
        {% if request.user.is_authenticated %}
        <ul class="menu">
            <li {% if section == "dashboard" %}class="selected"{% endif %}>
                <a href="{% url 'dashboard' %}">My dashboard</a>
            </li>
            <li {% if section == "images" %}class="selected"{% endif %}>
                <a href="{% url 'images:list' %}">Images</a>

            </li>
            <li {% if section == "people" %}class="selected"{% endif %}>
                <a href="{% url 'user_list' %}">People</a>
            </li>
        </ul>
        {% endif %}
 
 <span class="user">
 {% if request.user.is_authenticated %}
 Hello {{ request.user.first_name }},
 <a href="{% url 'logout' %}" style="color:rgb(226, 241, 12); font-size: 15px;font-weight: 600;">Logout</a>
 {% else %}
 <a href="{% url 'login' %}" style="color:rgb(226, 241, 12); font-size: 15px;font-weight: 600;">Log-in</a>
 <!-- <a href="{% url 'password_reset' %}" style="color:blanchedalmond;">Forget-password</a> -->
 {% endif %}
 </span>
    </div>
{% if messages %}
    <ul class="messages">
 {% for message in messages %}
        <li class="{{ message.tags }}">
            {{ message|safe }}
            <a href="#" class="close">✖</a>
        </li>
{% endfor %}
    </ul>
{% endif %}
    <div id="content">
        {% block content %}


        {% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src=" http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js "></script>

    <script>
        
        var csrftoken = $.cookie('csrftoken');
        console.log(csrftoken)
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }   
        });
    </script>
    {% block domready %}

    {% endblock %}
</body>
</html>

account/templates/cdnlines.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

account/templates/register.html
{% extends "base.html" %}
{% block title %}Create an account{% endblock %}
{% block content %}
 <h1>Create an account</h1>
 <p>Please, sign up using the following form:</p>
 <form action="." method="POST">
    {{ user_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Create my account"></p>
 </form>
{% endblock %}

account/templates/register_done.html
{% extends "base.html" %}
{% block title %}Welcome{% endblock %}
{% block content %}
 <h1>Welcome {{ new_user.first_name }}!</h1>
 <p>Your account has been successfully created. Now you can <a href="{% url 'login' %}">log in</a>.</p>
{% endblock %}